FROM alpine
ENV DB_NAME z-sys-rekam-medis
ENV DB_USER rekam-medis
ENV DB_PASS admin-rekam-medis
ENV DB_HOST db-rekam-medis
ENV DB_PORT 5432

RUN apk add nodejs npm
RUN npm config set unsafe-perm true
RUN npm i -g nodemon && mkdir /app
CMD [ "nodemon", "src/app" ]