FROM alpine
ENV DB_NAME z-sys-poli
ENV DB_USER poli
ENV DB_PASS admin-poli
ENV DB_HOST db-poli
ENV DB_PORT 5432

RUN apk add nodejs npm
RUN npm config set unsafe-perm true
RUN npm i -g nodemon && mkdir /app
CMD [ "nodemon", "src/app" ]