FROM alpine
ENV DB_NAME z-sys-apotik
ENV DB_USER apotik
ENV DB_PASS admin-apotik
ENV DB_HOST db-apotik
ENV DB_PORT 5432

RUN apk add nodejs npm
RUN npm config set unsafe-perm true
RUN npm i -g nodemon && mkdir /app
CMD [ "nodemon", "src/app" ]